import * as fs from 'fs';
import * as path from 'path';
import { RiskAssessment, PlaywrightSuiteOutput } from './schema';

export function generateReport(
  assessment: RiskAssessment,
  suiteOutput: PlaywrightSuiteOutput,
  outputPath?: string
): string {
  const timestamp = new Date().toISOString();
  const passRate = ((suiteOutput.stats.passed / suiteOutput.stats.total) * 100).toFixed(1);

  const recommendationEmoji = {
    SHIP: '✅',
    HOLD: '🛑',
    ESCALATE: '⚠️'
  }[assessment.release_recommendation];

  const riskEmoji = {
    LOW: '🟢',
    MEDIUM: '🟡',
    HIGH: '🟠',
    CRITICAL: '🔴'
  }[assessment.risk_level];

  const report = `# Release Risk Assessment
Generated: ${timestamp}

---

## ${recommendationEmoji} Recommendation: ${assessment.release_recommendation}
${riskEmoji} Risk Level: **${assessment.risk_level}** | Confidence: **${(assessment.confidence * 100).toFixed(0)}%**

---

## Stakeholder Summary
${assessment.stakeholder_summary}

---

## Test Suite Overview
| Metric | Value |
|--------|-------|
| Total Tests | ${suiteOutput.stats.total} |
| Passed | ${suiteOutput.stats.passed} |
| Failed | ${suiteOutput.stats.failed} |
| Flaky | ${suiteOutput.stats.flaky} |
| Pass Rate | ${passRate}% |

> ⚠️ **Pass rate is a vanity metric.** A ${passRate}% pass rate with a critical path failure is a HOLD.

---

## Risk Analysis

**Primary Concern:**
${assessment.primary_concern}

**Secondary Concern:**
${assessment.secondary_concern || 'None identified'}

**Critical Path Failures:**
${assessment.critical_path_failures.length > 0
  ? assessment.critical_path_failures.map(p => `- ${p}`).join('\n')
  : '- None'}

**Coverage Gaps Identified:**
${assessment.coverage_gaps.length > 0
  ? assessment.coverage_gaps.map(g => `- ${g}`).join('\n')
  : '- None identified'}

**Flakiness Signal:**
${assessment.flakiness_signal}

---

## Governance Note
> ${assessment.governance_note}

**Escalation Required:** ${assessment.escalation_required ? 'YES — human review required before proceeding' : 'No'}

---

*This assessment was generated by the AI Release Risk Scorer. The recommendation is advisory.
A human QA engineer must review and sign off before any production release.*
`;

  if (outputPath) {
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, report);
    console.log(`Report written to: ${outputPath}`);
  }

  return report;
}
